### ISSUE TITLE
unicode strings are not supported, please encode to bytes: '\x80'

### ISSUE THREAD

**Issue by chaitanyantr** [basicmicro/roboclaw_python_library#4]
![roboclaw error](https://user-images.githubusercontent.com/32541042/199316513-d7d8f9b3-d8a8-4d96-b57a-6a771bb8c0de.png)

Roboclaw python library error - I'm new to serial in python,but and I understood that the address needs to be in a different format. Can you please pour in your input?

An example file(provided in repo) I ran is:- **python3 roboclaw_simplepwm.py** 
Error:- **TypeError: Unicode strings are not supported, please encode to bytes: '\x80'**

**the log is:-** 

Traceback (most recent call last):
  File "roboclaw_simplepwm.py", line 13, in <module>
    rc.ForwardM1(address,32)	#1/4 power forward
  File "/home/krishna/capastone/claw_python/roboclaw_python_library-master/roboclaw_python/roboclaw.py", line 649, in ForwardM1
    return self._write1(address,self.Cmd.M1FORWARD,val)
  File "/home/krishna/capastone/claw_python/roboclaw_python_library-master/roboclaw_python/roboclaw.py", line 313, in _write1
    self._sendcommand(address,cmd)
  File "/home/krishna/capastone/claw_python/roboclaw_python_library-master/roboclaw_python/roboclaw.py", line 128, in _sendcommand
    self._port.write(chr(address))
  File "/home/krishna/.local/lib/python3.8/site-packages/serial/serialposix.py", line 616, in write
    d = to_bytes(data)
  File "/home/krishna/.local/lib/python3.8/site-packages/serial/serialutil.py", line 65, in to_bytes
    raise TypeError('unicode strings are not supported, please encode to bytes: {!r}'.format(seq))
TypeError: unicode strings are not supported, please encode to bytes: '\x80'

**Comment by Shubham07-bit** [comment]
try to encode all the serial commands, it will work.

**Comment by chaitanyantr** [comment]
the changes required for python3 are in roboclaw_3.py..import roboclaw_3.py.It solved my issue.
